[package]
name = "content"
version = "0.1.0"
edition = "2021"

[dependencies]
extism-pdk = { git = "https://github.com/extism/rust-pdk" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
crate_type = ["cdylib"]
